services:
  universe-database:
    container_name: universe_database
    image: mysql:8.0.34
    environment:
      MYSQL_USER: universe
      MYSQL_PASSWORD: universe
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: universe
      TZ: America/Sao_Paulo
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-time-zone=-03:00', '--log_bin_trust_function_creators=1']
    ports:
      - '3306:3306'
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    networks:
      - universe-network
networks:
  universe-network:
    name: universe_network
    driver: bridge
